### ISSUE TITLE
Suggested events: Add mention who will add event

### ISSUE THREAD

**Issue by MaxymVlasov** [itkpi/events-admin#6]

**Comment by webknjaz** [comment]
"Додати згадку про те, хто додасть івент"? Що це?

**Comment by MaxymVlasov** [comment]
@webknjaz 

Додати поле, що вказує на того, хто має додати івент.

Заодно слугуватиме маркером того, що івент перевірено.

**Comment by webknjaz** [comment]
Типу рев'ювер?

**Comment by MaxymVlasov** [comment]
@webknjaz ага

Диви яка структура: одна людина проходиться по всім івентам, вибирає які додати, які відхилити.

Ті що тре додати віддає на оформлення іншим, які вже і додають

**Comment by webknjaz** [comment]
Гм. Тоді розписати треба більше

**Comment by MaxymVlasov** [comment]
@webknjaz

Якщо коротко: потрібне поле, яке вміє в автодоповнення з БД юзерів тіми.

Все

**Comment by MaxymVlasov** [comment]
На сторінці списку запропонованих івентів.
Біля кожного івенту

**Comment by MaxymVlasov** [comment]
No longer relevant.
